### ISSUE TITLE
Allow trailing commas on imports and exports

### ISSUE THREAD

**Issue by dangaparker** [ArcadiaPower/eslint-config-arcadia#12]
https://eslint.org/docs/rules/comma-dangle

- [ ] Jabiru ArcadiaPower/jabiru#1528
- [ ] Peregrine ArcadiaPower/peregrine#511
- [ ] Osprey ArcadiaPower/osprey#1329
- [ ] Shrike ArcadiaPower/shrike#268
- [ ] Gryphon ArcadiaPower/gryphon#662
- [ ] Pigeon ArcadiaPower/pigeon#738
- [x] CatBird _no errors_
